"""
ISACSNet-Inspired Architecture for Bragg Edge ToF Reconstruction

Adapted from: "Deep learning-based compressed sampling reconstruction algorithm
for digitizing intensive neutron ToF signals" by Deng et al., 2025

This implementation adapts the ISACSNet architecture to reconstruct Bragg edge
transmission spectra from overlapping neutron ToF pulses generated by adaptive
chopper sequences.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Optional


class RandomProjectionModule(nn.Module):
    """
    Random projection module with learned convolutional layers.

    Replaces traditional random measurement matrices with learned filters
    that adaptively compress the signal based on structural characteristics.
    """

    def __init__(
        self,
        in_channels: int = 1,
        compression_ratio: float = 0.1,
        signal_length: int = 1024
    ):
        super().__init__()

        self.compression_ratio = compression_ratio
        n_filters = max(16, int(256 * compression_ratio))  # Scale filters with compression

        # Three sequential convolution layers as in ISACSNet
        # Original: kernels (1×8, 1×8, 1×4) with 256 filters each
        self.conv1 = nn.Conv1d(in_channels, n_filters, kernel_size=8, padding=4, stride=1)
        self.conv2 = nn.Conv1d(n_filters, n_filters, kernel_size=8, padding=4, stride=1)
        self.conv3 = nn.Conv1d(n_filters, n_filters, kernel_size=4, padding=2, stride=1)

        # Pooling to achieve compression
        self.pool = nn.AvgPool1d(kernel_size=int(1 / compression_ratio), stride=int(1 / compression_ratio))

        self.bn1 = nn.BatchNorm1d(n_filters)
        self.bn2 = nn.BatchNorm1d(n_filters)
        self.bn3 = nn.BatchNorm1d(n_filters)

    def forward(self, x):
        # x shape: (batch, 1, signal_length)
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))

        # Compress via pooling
        x = self.pool(x)

        return x


class DimensionRaisingModule(nn.Module):
    """
    Dimension-raising module with LeakyReLU activation.

    Expands the compressed representation to prepare for reconstruction.
    """

    def __init__(self, compressed_dim: int, raised_dim: int):
        super().__init__()

        self.fc1 = nn.Linear(compressed_dim, raised_dim)
        self.fc2 = nn.Linear(raised_dim, raised_dim)
        self.leaky_relu = nn.LeakyReLU(0.2)
        self.dropout = nn.Dropout(0.1)

    def forward(self, x):
        # Flatten if needed
        if len(x.shape) > 2:
            batch_size = x.shape[0]
            x = x.view(batch_size, -1)

        x = self.leaky_relu(self.fc1(x))
        x = self.dropout(x)
        x = self.leaky_relu(self.fc2(x))

        return x


class InceptionBlock(nn.Module):
    """
    Modified Inception block with multiscale temporal kernels.

    Original ISACSNet uses kernels: 1×3, 1×5, 1×7, 1×13
    """

    def __init__(self, in_channels: int, out_channels: int):
        super().__init__()

        # Reduce channels first
        self.bottleneck = nn.Conv1d(in_channels, out_channels // 4, kernel_size=1)

        # Multi-scale convolutions
        self.conv3 = nn.Conv1d(out_channels // 4, out_channels // 4, kernel_size=3, padding=1)
        self.conv5 = nn.Conv1d(out_channels // 4, out_channels // 4, kernel_size=5, padding=2)
        self.conv7 = nn.Conv1d(out_channels // 4, out_channels // 4, kernel_size=7, padding=3)
        self.conv13 = nn.Conv1d(out_channels // 4, out_channels // 4, kernel_size=13, padding=6)

        self.bn = nn.BatchNorm1d(out_channels)

    def forward(self, x):
        x = self.bottleneck(x)

        # Apply multi-scale convolutions in parallel
        x3 = self.conv3(x)
        x5 = self.conv5(x)
        x7 = self.conv7(x)
        x13 = self.conv13(x)

        # Concatenate outputs
        x = torch.cat([x3, x5, x7, x13], dim=1)
        x = self.bn(x)

        return F.relu(x)


class LSTMTemporalModule(nn.Module):
    """
    LSTM module to capture temporal dependencies in the ToF signal.

    Original ISACSNet uses 250 hidden cells.
    """

    def __init__(self, input_dim: int, hidden_dim: int = 250, num_layers: int = 2):
        super().__init__()

        self.lstm = nn.LSTM(
            input_dim,
            hidden_dim,
            num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=0.1
        )

        # Project back to input dimension
        self.fc = nn.Linear(hidden_dim * 2, input_dim)  # *2 for bidirectional

    def forward(self, x):
        # x shape: (batch, channels, length)
        # LSTM expects: (batch, length, features)
        x = x.transpose(1, 2)

        x, _ = self.lstm(x)
        x = self.fc(x)

        # Back to (batch, channels, length)
        x = x.transpose(1, 2)

        return x


class SelfAttentionModule(nn.Module):
    """
    Self-attention mechanism for long-range temporal features.

    Implements: attention = Softmax(Q @ K^T) @ V
    """

    def __init__(self, channels: int, reduction: int = 8):
        super().__init__()

        self.query = nn.Conv1d(channels, channels // reduction, kernel_size=1)
        self.key = nn.Conv1d(channels, channels // reduction, kernel_size=1)
        self.value = nn.Conv1d(channels, channels, kernel_size=1)

        self.gamma = nn.Parameter(torch.zeros(1))

    def forward(self, x):
        batch, channels, length = x.shape

        # Generate Q, K, V
        Q = self.query(x)  # (batch, C', L)
        K = self.key(x)    # (batch, C', L)
        V = self.value(x)  # (batch, C, L)

        # Compute attention scores
        Q = Q.permute(0, 2, 1)  # (batch, L, C')
        attention = torch.softmax(torch.bmm(Q, K), dim=-1)  # (batch, L, L)

        # Apply attention to values
        V = V.permute(0, 2, 1)  # (batch, L, C)
        out = torch.bmm(attention, V)  # (batch, L, C)
        out = out.permute(0, 2, 1)  # (batch, C, L)

        # Skip connection with learned weight
        out = self.gamma * out + x

        return out


class InitialReconstructionModule(nn.Module):
    """
    Initial reconstruction combining Inception blocks and LSTM.
    """

    def __init__(self, channels: int, signal_length: int):
        super().__init__()

        self.inception1 = InceptionBlock(channels, channels)
        self.inception2 = InceptionBlock(channels, channels)

        self.lstm = LSTMTemporalModule(channels, hidden_dim=128)

        self.conv_out = nn.Conv1d(channels, channels, kernel_size=3, padding=1)
        self.bn = nn.BatchNorm1d(channels)

    def forward(self, x, skip_input=None):
        identity = x

        x = self.inception1(x)
        x = self.inception2(x)

        x = self.lstm(x)

        x = self.conv_out(x)
        x = self.bn(x)

        # Skip connection
        if skip_input is not None:
            x = x + skip_input
        else:
            x = x + identity

        return F.relu(x)


class SecondaryReconstructionModule(nn.Module):
    """
    Secondary reconstruction with self-attention for refinement.
    """

    def __init__(self, channels: int):
        super().__init__()

        self.attention = SelfAttentionModule(channels)
        self.conv1 = nn.Conv1d(channels, channels * 2, kernel_size=3, padding=1)
        self.conv2 = nn.Conv1d(channels * 2, channels, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm1d(channels * 2)
        self.bn2 = nn.BatchNorm1d(channels)

    def forward(self, x):
        identity = x

        x = self.attention(x)

        x = F.relu(self.bn1(self.conv1(x)))
        x = self.bn2(self.conv2(x))

        # Skip connection
        x = x + identity

        return F.relu(x)


class ISACSNet(nn.Module):
    """
    Complete ISACSNet architecture adapted for Bragg edge reconstruction.

    Architecture:
    1. Random projection module (learned compression)
    2. Dimension-raising module
    3. Initial reconstruction (Inception + LSTM)
    4. Secondary reconstruction (self-attention)
    5. Final projection to output

    The network learns to reconstruct clean Bragg edge spectra from
    overlapping ToF measurements.
    """

    def __init__(
        self,
        signal_length: int = 1024,
        compression_ratio: float = 0.1,
        channels: int = 64,
        use_chopper_conditioning: bool = True
    ):
        super().__init__()

        self.signal_length = signal_length
        self.compression_ratio = compression_ratio
        self.use_chopper_conditioning = use_chopper_conditioning

        # Module 1: Random projection (compression)
        self.projection = RandomProjectionModule(
            in_channels=2 if use_chopper_conditioning else 1,
            compression_ratio=compression_ratio,
            signal_length=signal_length
        )

        # Calculate compressed dimensions
        compressed_length = int(signal_length * compression_ratio)
        n_filters = max(16, int(256 * compression_ratio))
        compressed_dim = compressed_length * n_filters

        # Module 2: Dimension raising
        raised_dim = compressed_dim * 2
        self.dimension_raising = DimensionRaisingModule(compressed_dim, raised_dim)

        # Reshape to prepare for convolutions
        self.reshape_channels = channels
        self.reshape_length = signal_length // 4  # Intermediate resolution
        self.fc_reshape = nn.Linear(raised_dim, self.reshape_channels * self.reshape_length)

        # Upsample to full resolution
        self.upsample = nn.Upsample(size=signal_length, mode='linear', align_corners=False)

        # Module 3: Initial reconstruction
        self.initial_reconstruction = InitialReconstructionModule(channels, signal_length)

        # Module 4: Secondary reconstruction
        self.secondary_reconstruction = SecondaryReconstructionModule(channels)

        # Final projection to output
        self.final_conv = nn.Conv1d(channels, 1, kernel_size=1)

    def forward(self, x, chopper_pattern: Optional[torch.Tensor] = None):
        """
        Forward pass.

        Args:
            x: Input signal (batch, 1, signal_length)
            chopper_pattern: Optional chopper pattern (batch, 1, signal_length)

        Returns:
            Reconstructed spectrum (batch, 1, signal_length)
        """
        # Concatenate chopper pattern if using conditioning
        if self.use_chopper_conditioning and chopper_pattern is not None:
            x = torch.cat([x, chopper_pattern], dim=1)

        # Save input for final skip connection
        input_residual = x[:, 0:1, :] if self.use_chopper_conditioning else x

        # Module 1: Compression via learned projection
        x = self.projection(x)

        # Module 2: Dimension raising
        x = self.dimension_raising(x)

        # Reshape for convolutional processing
        batch_size = x.shape[0]
        x = self.fc_reshape(x)
        x = x.view(batch_size, self.reshape_channels, self.reshape_length)

        # Upsample to full resolution
        x = self.upsample(x)

        # Module 3: Initial reconstruction with skip connection
        x = self.initial_reconstruction(x)

        # Module 4: Secondary reconstruction with attention
        x = self.secondary_reconstruction(x)

        # Final projection
        x = self.final_conv(x)

        # Final skip connection with input
        x = x + input_residual

        return x


def count_parameters(model):
    """Count trainable parameters in the model."""
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


if __name__ == "__main__":
    # Test the model
    model = ISACSNet(signal_length=1024, compression_ratio=0.1)
    print(f"Model parameters: {count_parameters(model):,}")

    # Test forward pass
    batch_size = 4
    x = torch.randn(batch_size, 1, 1024)
    chopper = torch.randint(0, 2, (batch_size, 1, 1024)).float()

    output = model(x, chopper)
    print(f"Input shape: {x.shape}")
    print(f"Output shape: {output.shape}")
